USE [master]
GO
/****** Object:  Database [TrekkingStore]    Script Date: 6/27/2022 8:39:00 PM ******/
CREATE DATABASE [TrekkingStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TrekkingStore', FILENAME = N'D:\sql\MSSQL15.SQLEXPRESS\MSSQL\DATA\TrekkingStore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TrekkingStore_log', FILENAME = N'D:\sql\MSSQL15.SQLEXPRESS\MSSQL\DATA\TrekkingStore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [TrekkingStore] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TrekkingStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TrekkingStore] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TrekkingStore] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TrekkingStore] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TrekkingStore] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TrekkingStore] SET ARITHABORT OFF 
GO
ALTER DATABASE [TrekkingStore] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TrekkingStore] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TrekkingStore] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TrekkingStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TrekkingStore] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TrekkingStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TrekkingStore] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TrekkingStore] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TrekkingStore] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TrekkingStore] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TrekkingStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TrekkingStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TrekkingStore] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TrekkingStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TrekkingStore] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TrekkingStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TrekkingStore] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TrekkingStore] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TrekkingStore] SET  MULTI_USER 
GO
ALTER DATABASE [TrekkingStore] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TrekkingStore] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TrekkingStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TrekkingStore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TrekkingStore] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TrekkingStore] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [TrekkingStore] SET QUERY_STORE = OFF
GO
USE [TrekkingStore]
GO
/****** Object:  Table [dbo].[order_items]    Script Date: 6/27/2022 8:39:00 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[order_items](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[order_id] [int] NOT NULL,
	[product_id] [int] NOT NULL,
	[quantity] [int] NOT NULL,
 CONSTRAINT [PK_order_items] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[orders]    Script Date: 6/27/2022 8:39:00 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[orders](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[user_id] [int] NOT NULL,
	[placed_at] [datetime] NULL,
 CONSTRAINT [PK_orders] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[products]    Script Date: 6/27/2022 8:39:00 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[products](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](255) NOT NULL,
	[price] [decimal](19, 4) NOT NULL,
	[path] [varchar](255) NULL,
	[description] [text] NULL,
 CONSTRAINT [PK_products] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[users]    Script Date: 6/27/2022 8:39:00 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[email] [varchar](255) NOT NULL,
	[first_name] [varchar](255) NULL,
	[last_name] [varchar](255) NULL,
	[password] [varchar](255) NOT NULL,
	[address] [varchar](255) NULL,
	[city] [varchar](255) NULL,
	[country] [varchar](255) NULL,
	[role] [varchar](255) NOT NULL,
 CONSTRAINT [PK_users] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [Unique_Email]    Script Date: 6/27/2022 8:39:01 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [Unique_Email] ON [dbo].[users]
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[order_items] ADD  CONSTRAINT [DF_order_items_quantity]  DEFAULT ((0)) FOR [quantity]
GO
ALTER TABLE [dbo].[products] ADD  CONSTRAINT [DF_products_price]  DEFAULT ((0)) FOR [price]
GO
ALTER TABLE [dbo].[users] ADD  CONSTRAINT [DF_users_role]  DEFAULT (user_name()) FOR [role]
GO
ALTER TABLE [dbo].[order_items]  WITH CHECK ADD  CONSTRAINT [FK_order_items_products] FOREIGN KEY([product_id])
REFERENCES [dbo].[products] ([id])
GO
ALTER TABLE [dbo].[order_items] CHECK CONSTRAINT [FK_order_items_products]
GO
ALTER TABLE [dbo].[order_items]  WITH CHECK ADD  CONSTRAINT [FK_orders_order_items] FOREIGN KEY([order_id])
REFERENCES [dbo].[orders] ([id])
GO
ALTER TABLE [dbo].[order_items] CHECK CONSTRAINT [FK_orders_order_items]
GO
ALTER TABLE [dbo].[orders]  WITH CHECK ADD  CONSTRAINT [FK_orders_users1] FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([id])
GO
ALTER TABLE [dbo].[orders] CHECK CONSTRAINT [FK_orders_users1]
GO
USE [master]
GO
ALTER DATABASE [TrekkingStore] SET  READ_WRITE 
GO
